name: CI/CD Flow

on:
  push:
    branches: 
        - develop

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 24
            - name: Check Project Structure and Verification
              run: |
                set -euo pipefail
                test -f package.json || (echo "package.json not found" && exit 1)
                test -f package-lock.json || (echo "package-lock.json not found" && exit 1)
                test -f vite.config.js || (echo "vite.config.js not found" && exit 1)
                test -d src || (echo "src directory not found" && exit 1)
                test -d public || (echo "public directory not found" && exit 1)
                if [ $? -eq 0 ]]; then
                  echo "Project structure verification done"
                  exit 0
                fi
            - name: Install dependencies
              run: npm ci
            - name: Run test 
              run: npx vitest
            - name: Build project
              run: npm run build
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: fe-build
                path: dist


    CD: 
        needs:
          - CI
        runs-on: ubuntu-latest
        steps:
            - name: SSH to server
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.SERVER_HOST }}
                port: 22
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_KEY }}
                script: |
                  echo "Checking for nginx installation"
                  if ! command -v nginx &> /dev/null; then
                    echo "nginx not found, installing..."
                    sudo apt update && sudo apt install -y nginx
                  else
                    echo "nginx installed"
                  fi
                  echo "nginx service status"
                  sudo systemctl status nginx
                  echo "nginx service running"
            - name: Download Artifact from CI
              uses: actions/download-artifact@v4
              with:
                name: fe-build
                path: dist
            - name: Copy build files to server
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_KEY }}
                source: "dist/*"
                target: "/temp"
                strip_components: 1
            - name: Move to web root
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.SERVER_HOST }}
                port: 22
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_KEY }}
                script: |
                  echo "Moving files to web root"
                  sudo mkdir -p /var/www/html/fptu-clothing-fe
                  sudo rm -rf /var/www/html/fptu-clothing-fe/*
                  sudo cp -r /tmp/* /var/www/html/fptu-clothing-fe/
                  sudo chown -R www-data:www-data /var/www/html/fptu-clothing-fe
                  rm -rf /tmp
              




